// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcUqWtnDflx9OhShUJewAVvR_zsE_BJSI',
    appId: '1:1052048596964:web:327a8ead80b457c3eaf1f1',
    messagingSenderId: '1052048596964',
    projectId: 'finstagram-udemy-23168',
    authDomain: 'finstagram-udemy-23168.firebaseapp.com',
    storageBucket: 'finstagram-udemy-23168.appspot.com',
    measurementId: 'G-MKYG3WEQV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7udAq7kGqptqwW5nxTScVMY6tg2DVPMY',
    appId: '1:1052048596964:android:e7f23965600aa3d9eaf1f1',
    messagingSenderId: '1052048596964',
    projectId: 'finstagram-udemy-23168',
    storageBucket: 'finstagram-udemy-23168.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuBXNPqGbjQp34rVI9q-Pvcka8HyjtEgA',
    appId: '1:1052048596964:ios:c9d89da74ec44649eaf1f1',
    messagingSenderId: '1052048596964',
    projectId: 'finstagram-udemy-23168',
    storageBucket: 'finstagram-udemy-23168.appspot.com',
    iosBundleId: 'com.example.finstagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuBXNPqGbjQp34rVI9q-Pvcka8HyjtEgA',
    appId: '1:1052048596964:ios:b37325f917773eafeaf1f1',
    messagingSenderId: '1052048596964',
    projectId: 'finstagram-udemy-23168',
    storageBucket: 'finstagram-udemy-23168.appspot.com',
    iosBundleId: 'com.example.finstagram.RunnerTests',
  );
}
